meta:
  # override this in your stub to set the environment name,
  # which is used for the deployment name
  #
  # i.e. my-release-production
  environment: ~

  stemcell:
    name: bosh-aws-xen-ubuntu
    version: latest

name: (( meta.environment ))

director_uuid: (( merge ))

releases: (( merge ))

networks: (( merge ))

jobs: (( merge ))

properties: (( merge ))

compilation:
  workers: 6
  network: oracle-xe-network
  reuse_compilation_vms: true
  cloud_properties: (( merge ))

update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 30000-900000
  update_watch_time: 5000-900000

resource_pools:
  - name: small_z1
    network: oracle-xe-network
    size: (( auto ))
    stemcell: (( meta.stemcell ))
    cloud_properties: (( merge ))
